[gspread_service_account]
type = "service_account"
project_id = "streamlit-visitor-log"
private_key_id = "6bbd6cd1ca291a4bc96b5720c5ac31b4e8abae0d"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCgGCKifc5Xb1N/
eHboFcJREjlmqbtBqO8uIldHBkaj4psaH2+iWssPFXQSu/8aBj1xYmWzkrnJs31f
Q63IFepoIiOnOmVM02QtwLWz6KbnC6FzN2M4TBS/pSp6kyeEOUxl7kpaqWy0Ruiq
79Egl1yY5i6PhsI7VUr3of9WQ+xbmBSxZXjm9CDz3EV8rsjp56NoSp4lmr6oBl5U
PhxIRqqPkEqXhHHP7DlVx16JXIDXVovJujpYxlsdr/f0JWHr/Prg9nBup80XDIYV
FRQw+F8hRaqWsYnemvqEN1GzMFjogKN/BE2BnFM3648i2LDnewaWa7y0xoa94lcV
Rl0yT6BZAgMBAAECggEAATj99ri4PTGz9QrB+bbE06Ksfoy4SeGU5gjMGtZA7tp5
rcLkstw3pcdXqhb2dUfr6zRBq5PoyFIPGI2nQ5prPl1YYVwQTvxkTPcmTBfwQl5z
3rHjF5h5JheIUgRSrm9Tlomx1qxpkJzkBP4s3i9ZvS8w1tbEH/jgSDDcBtgg83gc
Q8zN253phQK8lRbLoy/CM4l39z6uf7Tt8sBXxbXoUiP/Lz3jJowA2XfuTvjm6knX
Zmdb6IQdgBlNwUDchqJFyEJHNoT5XiUcaN6FhHCXf0N7YOFNonSTNIombzwP1040
lkz4lxM8oA5C/Zb37CbfCSFLc/O8PmJL5Pt4xCjWKQKBgQDUn/2lA9VfBxANzrdL
q03ckMfMU+28rh++8LBslZKTCC/AA0hOnrZyEvx/EY3E27En4GonvOqVlgT7eqIO
3WRD7axeq3OkUmyjDoWyr+r0dLPv5nbnDGODoy7iO1/QXOtjNeAA8HI+Mv38DxN6
fUzLa3ca/ZWhXCWGkiTSXPcerQKBgQDAwM+UP05BlLDOJXY4+FL+L+lfIu1Uo373
hzVxROWwseyF2ocgKC4otsHHu7pVE44FapY+JjRALX2J3z1dCI/OdnSJjenLncMm
ztfQhFI+gRp60qldo07pI1g9qCbvrZK/pKsh1YlfSoxeNtQKHAdDGF99h4a52CBp
j3mlnpBZ3QKBgE47I4cAdxREs/pwkW5M9BPwTSL3ymP+qP2G71K0Yb6pZ3A9hPAw
Yy5rn+1c1w2US4VBg61lS+aH0QN6JoBTot1/aElYye6uyPvhjv2kzkztV3swD5WJ
MGAxvUFN2T3/wje5jdaqoU4TUvHX1jHeQlAiFSugG9rH3aK6yMOBowbtAoGASKSh
1rIhERAzrg1qR8A2rvtpjWRBY4OWpzz6xCx+ECCODkg0Ysch1lBCKb8zUzribGIm
K1gEmydJx7stijFe2SXFd83XDdjwImET7s7fnBTV4PIhyFtysuSSLfKAchXNV5J8
uGycsCANVLh/Iyw7BGtcGZgJC2NLm9zpsKRYrLUCgYBI71StRg3z2zV18rKM8PB/
TmBGyoBnMSoT1Do4l07MPYEVFz7/7SfdHLk6LZTs0o5b8VGX+jY5K2fZQjBuNB+8
NFSLmQG0ELWQcTubOB4b/GjphNw+BdP1LetGC3OFC3ETnbVm/rwWgzat8jaL+Ygo
7QD/hN96sjm4bSfRSqqUCA==
-----END PRIVATE KEY-----"""
client_email = "streamlit-visitor-log@streamlit-visitor-log.iam.gserviceaccount.com"
client_id = "106511861646722260410"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/streamlit-visitor-log%40streamlit-visitor-log.iam.gserviceaccount.com"
